[deps]
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
DistributedArrays = "0.6"
Documenter = "1"

[sources.DistributedArrays]
path = ".."
